version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - run:
          name: Run Checkstyle
          command: |-
            mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/site/checkstyle.html
          destination: checkstyle-report
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p output
            mv target/site/apidocs/* output/
            git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/frehou/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            rm -rf *
            mv ../output/* .
            git add .
            git commit -m "Update Javadoc"
            git push https://$GITHUB_TOKEN@github.com/frehou/ceri-m1-techniques-de-test.git gh-pages

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-java
    # - deploy:
    #     requires:
    #       - test-java
