version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run tests and upload coverage to Codecov
          command: |
            mvn verify
            bash <(curl -s https://codecov.io/bash) -t maven -x YOUR_CODECOV_TOKEN
            codecov -f target/surefire-reports
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: deploy
          command: ./deploy.sh
workflows:
  build-and-test:
    jobs:
      - test-java
      # Ajouter d'autres jobs si nécessaire